Failed switch to snapshot #PSBM-67062
error: "Unable to lock ENTER operation"
Enter lock should be used only for external operations and should be skipped
for internal one.

Signed-off-by: Igor Sukhih <igor@virtuozzo.com>